# Generated by Django 5.1 on 2024-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('discord', models.CharField(max_length=128)),
                ('payments', models.JSONField(default={})),
            ],
        ),
    ]
