# Generated by Django 5.1 on 2024-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payments',
            field=models.JSONField(default={'0': '0'}),
        ),
    ]
